### ISSUE TITLE
AI can't use LLAMA3.1

### ISSUE THREAD

**Issue by viperqao1st** [shasankp000/AI-Player#10]

**Comment by shasankp000** [comment]
Yes, since as it says on the mod description page on modrinth, the mod currently relies on gemma2.

However upcoming updates plan to resolve this by shifting to llama3.2

Please wait till mid of December as I have college exams of 8 subjects next month.

Once my exams are over I can resume active development and roll out updates and fixes.

**Comment by shasankp000** [comment]
Will close this issue soon if there isn't anything else to report.
